name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: "Build release binary"
        run: "cargo build --release"

      - uses: actions/upload-artifact@v7
        with:
          path: "target/release/yg"
          if-no-files-found: "error"
          archive: false
